2015/07/17 17:41:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "isite/contact".' in Z:\domains\localhost\blogYii\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('isite/contact')
#1 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blogYii/isite/contact
---
2015/07/17 18:14:24 [error] [php] session_regenerate_id(): Session object destruction failed (Z:\domains\localhost\blogYii\framework\web\CHttpSession.php:182)
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\web\auth\CWebUser.php(233): CWebUser->changeIdentity()
#1 Z:\domains\localhost\blogYii\framework\gii\models\LoginForm.php(43): CWebUser->login()
#2 Z:\domains\localhost\blogYii\framework\gii\controllers\DefaultController.php(43): LoginForm->login()
#3 Z:\domains\localhost\blogYii\framework\web\actions\CInlineAction.php(49): DefaultController->actionLogin()
#4 Z:\domains\localhost\blogYii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 Z:\domains\localhost\blogYii\framework\web\CController.php(286): DefaultController->runAction()
#6 Z:\domains\localhost\blogYii\framework\web\CController.php(265): DefaultController->runActionWithFilters()
#7 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(282): DefaultController->run()
#8 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 Z:\domains\localhost\blogYii\index.php(11): CWebApplication->run()
REQUEST_URI=/blogYii/index.php/gii/default/login
2015/07/17 19:07:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "admin".' in Z:\domains\localhost\blogYii\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('admin')
#1 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blogYii/index.php/admin
---
2015/07/18 18:22:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "page?view=about".' in Z:\domains\localhost\blogYii\framework\web\CController.php:483
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\web\CController.php(270): CController->missingAction('page?view=about')
#1 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(282): CController->run('page?view=about')
#2 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/page?view=...')
#3 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#5 {main}
REQUEST_URI=/blogYii/about
---
2015/07/18 18:23:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "page?view=about".' in Z:\domains\localhost\blogYii\framework\web\CController.php:483
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\web\CController.php(270): CController->missingAction('page?view=about')
#1 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(282): CController->run('page?view=about')
#2 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/page?view=...')
#3 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#5 {main}
REQUEST_URI=/blogYii/index.php/about
---
2015/07/18 18:24:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "page?view=about".' in Z:\domains\localhost\blogYii\framework\web\CController.php:483
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\web\CController.php(270): CController->missingAction('page?view=about')
#1 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(282): CController->run('page?view=about')
#2 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/page?view=...')
#3 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#5 {main}
REQUEST_URI=/blogYii/index.php/about
---
2015/07/18 18:25:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "index.php/site/page?view=about".' in Z:\domains\localhost\blogYii\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('index.php/site/...')
#1 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blogYii/about
---
2015/07/19 17:22:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "test".' in Z:\domains\localhost\blogYii\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('test')
#1 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blogYii/test
---
2015/07/19 17:41:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "Туцы".' in Z:\domains\localhost\blogYii\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('\xD0\xA2\xD1\x83\xD1\x86\xD1\x8B')
#1 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blogYii/%D0%A2%D1%83%D1%86%D1%8B
---
2015/07/20 18:48:14 [error] [exception.CException] exception 'CException' with message 'Контроллер TestNewsController не может найти представление "data".' in Z:\domains\localhost\blogYii\framework\web\CController.php:878
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\web\CController.php(782): CController->renderPartial('data', Array, true)
#1 Z:\domains\localhost\blogYii\protected\controllers\TestNewsController.php(11): CController->render('data', Array)
#2 Z:\domains\localhost\blogYii\framework\web\actions\CInlineAction.php(49): TestNewsController->actionData()
#3 Z:\domains\localhost\blogYii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 Z:\domains\localhost\blogYii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 Z:\domains\localhost\blogYii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(282): CController->run('data')
#7 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('testnews/data')
#8 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#9 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#10 {main}
REQUEST_URI=/blogYii/testnews/data
---
2015/07/20 18:53:14 [error] [exception.CException] exception 'CException' with message 'Контроллер TestNewsController не может найти представление "data".' in Z:\domains\localhost\blogYii\framework\web\CController.php:878
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\web\CController.php(782): CController->renderPartial('data', Array, true)
#1 Z:\domains\localhost\blogYii\protected\controllers\TestNewsController.php(11): CController->render('data', Array)
#2 Z:\domains\localhost\blogYii\framework\web\actions\CInlineAction.php(49): TestNewsController->actionData()
#3 Z:\domains\localhost\blogYii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 Z:\domains\localhost\blogYii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 Z:\domains\localhost\blogYii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(282): CController->run('data')
#7 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('testnews/data')
#8 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#9 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#10 {main}
REQUEST_URI=/blogYii/testnews/data
---
2015/07/20 18:55:57 [error] [exception.CException] exception 'CException' with message 'Контроллер TestNewsController не может найти представление "data".' in Z:\domains\localhost\blogYii\framework\web\CController.php:878
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\web\CController.php(782): CController->renderPartial('data', Array, true)
#1 Z:\domains\localhost\blogYii\protected\controllers\TestNewsController.php(11): CController->render('data', Array)
#2 Z:\domains\localhost\blogYii\framework\web\actions\CInlineAction.php(49): TestNewsController->actionData()
#3 Z:\domains\localhost\blogYii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 Z:\domains\localhost\blogYii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 Z:\domains\localhost\blogYii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(282): CController->run('data')
#7 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('testnews/data')
#8 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#9 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#10 {main}
REQUEST_URI=/blogYii/testnews/data
---
2015/07/21 16:45:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "rendertable".' in Z:\domains\localhost\blogYii\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('rendertable')
#1 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blogYii/rendertable
---
2015/07/21 16:47:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "Rendertable".' in Z:\domains\localhost\blogYii\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('Rendertable')
#1 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blogYii/Rendertable
---
2015/07/21 16:47:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "rendertable".' in Z:\domains\localhost\blogYii\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('rendertable')
#1 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blogYii/rendertable
---
2015/07/23 19:09:13 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "form".' in Z:\domains\localhost\blogYii\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('form')
#1 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blogYii/form
---
2015/07/23 19:09:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "form/login".' in Z:\domains\localhost\blogYii\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('form/login')
#1 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blogYii/form/login
---
2015/07/23 19:14:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "form/login".' in Z:\domains\localhost\blogYii\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('form/login')
#1 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blogYii/form/login
---
2015/07/23 19:14:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "form/login".' in Z:\domains\localhost\blogYii\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('form/login')
#1 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blogYii/form/login
---
2015/07/23 19:17:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "form/login".' in Z:\domains\localhost\blogYii\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('form/login')
#1 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blogYii/form/login
---
2015/07/23 19:20:13 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "form/login".' in Z:\domains\localhost\blogYii\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('form/login')
#1 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blogYii/form/login
---
2015/07/23 19:23:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "form/login".' in Z:\domains\localhost\blogYii\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('form/login')
#1 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blogYii/form/login
---
2015/07/23 19:25:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "form/login".' in Z:\domains\localhost\blogYii\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('form/login')
#1 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blogYii/form/login
---
2015/07/23 19:26:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "form/login".' in Z:\domains\localhost\blogYii\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('form/login')
#1 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blogYii/form/login
---
2015/07/23 19:27:06 [error] [exception.CException] exception 'CException' with message 'Контроллер FormController не может найти представление "login".' in Z:\domains\localhost\blogYii\framework\web\CController.php:878
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\web\CController.php(782): CController->renderPartial('login', Array, true)
#1 Z:\domains\localhost\blogYii\protected\controllers\FormController.php(13): CController->render('login', Array)
#2 Z:\domains\localhost\blogYii\framework\web\actions\CInlineAction.php(49): FormController->actionLogin()
#3 Z:\domains\localhost\blogYii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 Z:\domains\localhost\blogYii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 Z:\domains\localhost\blogYii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(282): CController->run('login')
#7 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('form/login')
#8 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#9 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#10 {main}
REQUEST_URI=/blogYii/form/login
---
2015/07/24 16:48:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "login".' in Z:\domains\localhost\blogYii\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('login')
#1 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blogYii/login
---
2015/07/24 17:00:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "login".' in Z:\domains\localhost\blogYii\framework\web\CController.php:483
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\web\CController.php(270): CController->missingAction('login')
#1 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(282): CController->run('login')
#2 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('form/login')
#3 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#5 {main}
REQUEST_URI=/blogYii/form/login
---
2015/07/24 17:06:18 [error] [exception.CException] exception 'CException' with message 'Не определено свойство "ContactTestForm.subjecte".' in Z:\domains\localhost\blogYii\framework\base\CComponent.php:130
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\web\helpers\CHtml.php(2728): CComponent->__get('subjecte')
#1 Z:\domains\localhost\blogYii\framework\web\helpers\CHtml.php(2451): CHtml::resolveValue(Object(ContactTestForm), 'subjecte')
#2 Z:\domains\localhost\blogYii\framework\web\helpers\CHtml.php(1533): CHtml::activeInputField('text', Object(ContactTestForm), 'subjecte', Array)
#3 Z:\domains\localhost\blogYii\framework\web\widgets\CActiveForm.php(792): CHtml::activeTextField(Object(ContactTestForm), 'subjecte', Array)
#4 Z:\domains\localhost\blogYii\protected\views\form\contact.php(16): CActiveForm->textField(Object(ContactTestForm), 'subjecte')
#5 Z:\domains\localhost\blogYii\framework\web\CBaseController.php(126): require('Z:\\domains\\loca...')
#6 Z:\domains\localhost\blogYii\framework\web\CBaseController.php(95): CBaseController->renderInternal('Z:\\domains\\loca...', Array, true)
#7 Z:\domains\localhost\blogYii\framework\web\CController.php(869): CBaseController->renderFile('Z:\\domains\\loca...', Array, true)
#8 Z:\domains\localhost\blogYii\framework\web\CController.php(782): CController->renderPartial('contact', Array, true)
#9 Z:\domains\localhost\blogYii\protected\controllers\FormController.php(15): CController->render('contact', Array)
#10 Z:\domains\localhost\blogYii\framework\web\actions\CInlineAction.php(49): FormController->actionContact()
#11 Z:\domains\localhost\blogYii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#12 Z:\domains\localhost\blogYii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#13 Z:\domains\localhost\blogYii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(282): CController->run('contact')
#15 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('form/contact')
#16 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#17 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#18 {main}
REQUEST_URI=/blogYii/form/contact
---
2015/07/24 17:19:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "captcha".' in Z:\domains\localhost\blogYii\framework\web\CController.php:483
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\web\CController.php(270): CController->missingAction('captcha')
#1 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(282): CController->run('captcha')
#2 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('form/captcha')
#3 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#5 {main}
REQUEST_URI=/blogYii/index.php/form/captcha?v=55b24969dddc6
HTTP_REFERER=http://localhost/blogYii/form/contact
---
2015/07/27 17:06:16 [error] [php] Invalid argument supplied for foreach() (Z:\domains\localhost\blogYii\framework\base\CModel.php:284)
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\web\widgets\CActiveForm.php(567): LoginTestForm->getSafeAttributeNames()
#1 Z:\domains\localhost\blogYii\protected\views\form\login.php(7): CActiveForm->errorSummary()
#2 Z:\domains\localhost\blogYii\framework\web\CBaseController.php(126): require()
#3 Z:\domains\localhost\blogYii\framework\web\CBaseController.php(95): FormController->renderInternal()
#4 Z:\domains\localhost\blogYii\framework\web\CController.php(869): FormController->renderFile()
#5 Z:\domains\localhost\blogYii\framework\web\CController.php(782): FormController->renderPartial()
#6 Z:\domains\localhost\blogYii\protected\controllers\FormController.php(79): FormController->render()
#7 Z:\domains\localhost\blogYii\framework\web\actions\CInlineAction.php(49): FormController->actionLogin()
#8 Z:\domains\localhost\blogYii\framework\web\CController.php(308): CInlineAction->runWithParams()
#9 Z:\domains\localhost\blogYii\framework\web\CController.php(286): FormController->runAction()
#10 Z:\domains\localhost\blogYii\framework\web\CController.php(265): FormController->runActionWithFilters()
#11 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(282): FormController->run()
#12 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#13 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#14 Z:\domains\localhost\blogYii\index.php(11): CWebApplication->run()
REQUEST_URI=/blogYii/form/login
2015/07/27 17:10:18 [error] [php] Invalid argument supplied for foreach() (Z:\domains\localhost\blogYii\framework\base\CModel.php:284)
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\web\widgets\CActiveForm.php(567): LoginTestForm->getSafeAttributeNames()
#1 Z:\domains\localhost\blogYii\protected\views\form\login.php(7): CActiveForm->errorSummary()
#2 Z:\domains\localhost\blogYii\framework\web\CBaseController.php(126): require()
#3 Z:\domains\localhost\blogYii\framework\web\CBaseController.php(95): FormController->renderInternal()
#4 Z:\domains\localhost\blogYii\framework\web\CController.php(869): FormController->renderFile()
#5 Z:\domains\localhost\blogYii\framework\web\CController.php(782): FormController->renderPartial()
#6 Z:\domains\localhost\blogYii\protected\controllers\FormController.php(79): FormController->render()
#7 Z:\domains\localhost\blogYii\framework\web\actions\CInlineAction.php(49): FormController->actionLogin()
#8 Z:\domains\localhost\blogYii\framework\web\CController.php(308): CInlineAction->runWithParams()
#9 Z:\domains\localhost\blogYii\framework\web\CController.php(286): FormController->runAction()
#10 Z:\domains\localhost\blogYii\framework\web\CController.php(265): FormController->runActionWithFilters()
#11 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(282): FormController->run()
#12 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#13 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#14 Z:\domains\localhost\blogYii\index.php(11): CWebApplication->run()
REQUEST_URI=/blogYii/form/login
2015/07/27 17:10:23 [error] [php] Invalid argument supplied for foreach() (Z:\domains\localhost\blogYii\framework\base\CModel.php:284)
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\web\widgets\CActiveForm.php(567): LoginTestForm->getSafeAttributeNames()
#1 Z:\domains\localhost\blogYii\protected\views\form\login.php(7): CActiveForm->errorSummary()
#2 Z:\domains\localhost\blogYii\framework\web\CBaseController.php(126): require()
#3 Z:\domains\localhost\blogYii\framework\web\CBaseController.php(95): FormController->renderInternal()
#4 Z:\domains\localhost\blogYii\framework\web\CController.php(869): FormController->renderFile()
#5 Z:\domains\localhost\blogYii\framework\web\CController.php(782): FormController->renderPartial()
#6 Z:\domains\localhost\blogYii\protected\controllers\FormController.php(79): FormController->render()
#7 Z:\domains\localhost\blogYii\framework\web\actions\CInlineAction.php(49): FormController->actionLogin()
#8 Z:\domains\localhost\blogYii\framework\web\CController.php(308): CInlineAction->runWithParams()
#9 Z:\domains\localhost\blogYii\framework\web\CController.php(286): FormController->runAction()
#10 Z:\domains\localhost\blogYii\framework\web\CController.php(265): FormController->runActionWithFilters()
#11 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(282): FormController->run()
#12 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#13 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#14 Z:\domains\localhost\blogYii\index.php(11): CWebApplication->run()
REQUEST_URI=/blogYii/form/login
2015/07/27 17:12:20 [error] [php] Invalid argument supplied for foreach() (Z:\domains\localhost\blogYii\framework\base\CModel.php:284)
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\web\widgets\CActiveForm.php(567): LoginTestForm->getSafeAttributeNames()
#1 Z:\domains\localhost\blogYii\protected\views\form\login.php(7): CActiveForm->errorSummary()
#2 Z:\domains\localhost\blogYii\framework\web\CBaseController.php(126): require()
#3 Z:\domains\localhost\blogYii\framework\web\CBaseController.php(95): FormController->renderInternal()
#4 Z:\domains\localhost\blogYii\framework\web\CController.php(869): FormController->renderFile()
#5 Z:\domains\localhost\blogYii\framework\web\CController.php(782): FormController->renderPartial()
#6 Z:\domains\localhost\blogYii\protected\controllers\FormController.php(79): FormController->render()
#7 Z:\domains\localhost\blogYii\framework\web\actions\CInlineAction.php(49): FormController->actionLogin()
#8 Z:\domains\localhost\blogYii\framework\web\CController.php(308): CInlineAction->runWithParams()
#9 Z:\domains\localhost\blogYii\framework\web\CController.php(286): FormController->runAction()
#10 Z:\domains\localhost\blogYii\framework\web\CController.php(265): FormController->runActionWithFilters()
#11 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(282): FormController->run()
#12 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#13 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#14 Z:\domains\localhost\blogYii\index.php(11): CWebApplication->run()
REQUEST_URI=/blogYii/form/login
2015/07/27 17:13:01 [error] [exception.CException] exception 'CException' with message 'Не определено свойство "LoginTestForm.login".' in Z:\domains\localhost\blogYii\framework\base\CComponent.php:130
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\web\helpers\CHtml.php(2728): CComponent->__get('login')
#1 Z:\domains\localhost\blogYii\framework\web\helpers\CHtml.php(2451): CHtml::resolveValue(Object(LoginTestForm), 'login')
#2 Z:\domains\localhost\blogYii\framework\web\helpers\CHtml.php(1533): CHtml::activeInputField('text', Object(LoginTestForm), 'login', Array)
#3 Z:\domains\localhost\blogYii\framework\web\widgets\CActiveForm.php(792): CHtml::activeTextField(Object(LoginTestForm), 'login', Array)
#4 Z:\domains\localhost\blogYii\protected\views\form\login.php(11): CActiveForm->textField(Object(LoginTestForm), 'login')
#5 Z:\domains\localhost\blogYii\framework\web\CBaseController.php(126): require('Z:\\domains\\loca...')
#6 Z:\domains\localhost\blogYii\framework\web\CBaseController.php(95): CBaseController->renderInternal('Z:\\domains\\loca...', Array, true)
#7 Z:\domains\localhost\blogYii\framework\web\CController.php(869): CBaseController->renderFile('Z:\\domains\\loca...', Array, true)
#8 Z:\domains\localhost\blogYii\framework\web\CController.php(782): CController->renderPartial('login', Array, true)
#9 Z:\domains\localhost\blogYii\protected\controllers\FormController.php(79): CController->render('login', Array)
#10 Z:\domains\localhost\blogYii\framework\web\actions\CInlineAction.php(49): FormController->actionLogin()
#11 Z:\domains\localhost\blogYii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#12 Z:\domains\localhost\blogYii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#13 Z:\domains\localhost\blogYii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(282): CController->run('login')
#15 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('form/login')
#16 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#17 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#18 {main}
REQUEST_URI=/blogYii/form/login
---
2015/07/27 17:18:40 [error] [exception.CException] exception 'CException' with message 'Не определено свойство "LoginTestForm.login".' in Z:\domains\localhost\blogYii\framework\base\CComponent.php:130
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\web\helpers\CHtml.php(2728): CComponent->__get('login')
#1 Z:\domains\localhost\blogYii\framework\web\helpers\CHtml.php(2451): CHtml::resolveValue(Object(LoginTestForm), 'login')
#2 Z:\domains\localhost\blogYii\framework\web\helpers\CHtml.php(1533): CHtml::activeInputField('text', Object(LoginTestForm), 'login', Array)
#3 Z:\domains\localhost\blogYii\framework\web\widgets\CActiveForm.php(792): CHtml::activeTextField(Object(LoginTestForm), 'login', Array)
#4 Z:\domains\localhost\blogYii\protected\views\form\login.php(11): CActiveForm->textField(Object(LoginTestForm), 'login')
#5 Z:\domains\localhost\blogYii\framework\web\CBaseController.php(126): require('Z:\\domains\\loca...')
#6 Z:\domains\localhost\blogYii\framework\web\CBaseController.php(95): CBaseController->renderInternal('Z:\\domains\\loca...', Array, true)
#7 Z:\domains\localhost\blogYii\framework\web\CController.php(869): CBaseController->renderFile('Z:\\domains\\loca...', Array, true)
#8 Z:\domains\localhost\blogYii\framework\web\CController.php(782): CController->renderPartial('login', Array, true)
#9 Z:\domains\localhost\blogYii\protected\controllers\FormController.php(79): CController->render('login', Array)
#10 Z:\domains\localhost\blogYii\framework\web\actions\CInlineAction.php(49): FormController->actionLogin()
#11 Z:\domains\localhost\blogYii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#12 Z:\domains\localhost\blogYii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#13 Z:\domains\localhost\blogYii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(282): CController->run('login')
#15 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('form/login')
#16 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#17 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#18 {main}
REQUEST_URI=/blogYii/form/login
---
2015/07/27 18:43:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "contractconstruct".' in Z:\domains\localhost\blogYii\framework\web\CController.php:483
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\web\CController.php(270): CController->missingAction('contractconstru...')
#1 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(282): CController->run('contractconstru...')
#2 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('form/contractco...')
#3 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#5 {main}
REQUEST_URI=/blogYii/form/contractconstruct
---
2015/07/27 18:45:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "contractconstruct".' in Z:\domains\localhost\blogYii\framework\web\CController.php:483
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\web\CController.php(270): CController->missingAction('contractconstru...')
#1 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(282): CController->run('contractconstru...')
#2 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('form/contractco...')
#3 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#5 {main}
REQUEST_URI=/blogYii/form/contractconstruct
---
2015/07/27 18:50:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "contractconstruct".' in Z:\domains\localhost\blogYii\framework\web\CController.php:483
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\web\CController.php(270): CController->missingAction('contractconstru...')
#1 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(282): CController->run('contractconstru...')
#2 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('form/contractco...')
#3 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#5 {main}
REQUEST_URI=/blogYii/form/contractconstruct
---
2015/07/27 18:53:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "contractconstruct".' in Z:\domains\localhost\blogYii\framework\web\CController.php:483
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\web\CController.php(270): CController->missingAction('contractconstru...')
#1 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(282): CController->run('contractconstru...')
#2 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('form/contractco...')
#3 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#5 {main}
REQUEST_URI=/blogYii/form/contractconstruct
---
2015/07/27 18:53:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "contractconstruct".' in Z:\domains\localhost\blogYii\framework\web\CController.php:483
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\web\CController.php(270): CController->missingAction('contractconstru...')
#1 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(282): CController->run('contractconstru...')
#2 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('form/contractco...')
#3 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#5 {main}
REQUEST_URI=/blogYii/form/contractconstruct
---
2015/07/27 18:56:30 [error] [php] include(textArea.php): failed to open stream: No such file or directory (Z:\domains\localhost\blogYii\framework\YiiBase.php:432)
Stack trace:
#0 unknown(0): spl_autoload_call()
#1 Z:\domains\localhost\blogYii\framework\YiiBase.php(303): class_exists()
#2 Z:\domains\localhost\blogYii\framework\web\CWidgetFactory.php(146): import()
#3 Z:\domains\localhost\blogYii\framework\web\CBaseController.php(146): CWidgetFactory->createWidget()
#4 Z:\domains\localhost\blogYii\framework\web\CBaseController.php(180): FormController->createWidget()
#5 Z:\domains\localhost\blogYii\framework\web\form\CFormInputElement.php(240): FormController->widget()
#6 Z:\domains\localhost\blogYii\framework\web\form\CFormInputElement.php(194): CFormInputElement->renderInput()
#7 Z:\domains\localhost\blogYii\framework\web\form\CForm.php(543): CFormInputElement->render()
#8 Z:\domains\localhost\blogYii\framework\web\form\CForm.php(505): CForm->renderElement()
#9 Z:\domains\localhost\blogYii\framework\web\form\CForm.php(489): CForm->renderElements()
#10 Z:\domains\localhost\blogYii\framework\web\form\CForm.php(405): CForm->renderBody()
#11 Z:\domains\localhost\blogYii\framework\web\form\CFormElement.php(61): CForm->render()
#12 Z:\domains\localhost\blogYii\protected\views\form\contactconstruct.php(1): CForm->__toString()
#13 Z:\domains\localhost\blogYii\framework\web\CBaseController.php(126): require()
#14 Z:\domains\localhost\blogYii\framework\web\CBaseController.php(95): FormController->renderInternal()
#15 Z:\domains\localhost\blogYii\framework\web\CController.php(869): FormController->renderFile()
#16 Z:\domains\localhost\blogYii\framework\web\CController.php(782): FormController->renderPartial()
#17 Z:\domains\localhost\blogYii\protected\controllers\FormController.php(95): FormController->render()
#18 Z:\domains\localhost\blogYii\framework\web\actions\CInlineAction.php(49): FormController->actionContactconstruct()
#19 Z:\domains\localhost\blogYii\framework\web\CController.php(308): CInlineAction->runWithParams()
#20 Z:\domains\localhost\blogYii\framework\web\CController.php(286): FormController->runAction()
#21 Z:\domains\localhost\blogYii\framework\web\CController.php(265): FormController->runActionWithFilters()
#22 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(282): FormController->run()
#23 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#24 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#25 Z:\domains\localhost\blogYii\index.php(11): CWebApplication->run()
REQUEST_URI=/blogYii/form/contactconstruct
2015/07/28 16:35:09 [error] [exception.CException] exception 'CException' with message 'Не определено свойство "CForm.validate".' in Z:\domains\localhost\blogYii\framework\web\form\CFormElement.php:85
Stack trace:
#0 Z:\domains\localhost\blogYii\protected\controllers\FormController.php(88): CFormElement->__get('validate')
#1 Z:\domains\localhost\blogYii\framework\web\actions\CInlineAction.php(49): FormController->actionContactconstruct()
#2 Z:\domains\localhost\blogYii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 Z:\domains\localhost\blogYii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 Z:\domains\localhost\blogYii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(282): CController->run('contactconstruc...')
#6 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('form/contactcon...')
#7 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#8 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#9 {main}
REQUEST_URI=/blogYii/form/contactconstruct
---
2015/07/28 16:39:46 [error] [exception.CException] exception 'CException' with message 'Не определено свойство "ContactTestForm.validate".' in Z:\domains\localhost\blogYii\framework\base\CComponent.php:130
Stack trace:
#0 Z:\domains\localhost\blogYii\protected\controllers\FormController.php(88): CComponent->__get('validate')
#1 Z:\domains\localhost\blogYii\framework\web\actions\CInlineAction.php(49): FormController->actionContactconstruct()
#2 Z:\domains\localhost\blogYii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 Z:\domains\localhost\blogYii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 Z:\domains\localhost\blogYii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(282): CController->run('contactconstruc...')
#6 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('form/contactcon...')
#7 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#8 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#9 {main}
REQUEST_URI=/blogYii/form/contactconstruct
---
2015/07/28 17:48:03 [error] [php] include(RegisterTestForm.php): failed to open stream: No such file or directory (Z:\domains\localhost\blogYii\framework\YiiBase.php:432)
Stack trace:
#0 Z:\domains\localhost\blogYii\protected\controllers\FormController.php(118): spl_autoload_call()
#1 Z:\domains\localhost\blogYii\framework\web\actions\CInlineAction.php(49): FormController->actionRegisterconstruct()
#2 Z:\domains\localhost\blogYii\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 Z:\domains\localhost\blogYii\framework\web\CController.php(286): FormController->runAction()
#4 Z:\domains\localhost\blogYii\framework\web\CController.php(265): FormController->runActionWithFilters()
#5 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(282): FormController->run()
#6 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#7 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#8 Z:\domains\localhost\blogYii\index.php(11): CWebApplication->run()
REQUEST_URI=/blogYii/form/registerconstruct
2015/07/29 16:39:59 [error] [php] Invalid argument supplied for foreach() (Z:\domains\localhost\blogYii\protected\controllers\DatabaseController.php:21)
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\web\CController.php(286): DatabaseController->runAction()
#1 Z:\domains\localhost\blogYii\framework\web\CController.php(265): DatabaseController->runActionWithFilters()
#2 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(282): DatabaseController->run()
#3 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#5 Z:\domains\localhost\blogYii\index.php(11): CWebApplication->run()
REQUEST_URI=/blogYii/database/dao
2015/07/29 16:45:56 [error] [exception.CException] exception 'CException' with message 'В классе CDbCommand и его поведениях не найден метод или замыкание с именем "queryRowl".' in Z:\domains\localhost\blogYii\framework\base\CComponent.php:266
Stack trace:
#0 Z:\domains\localhost\blogYii\protected\controllers\DatabaseController.php(32): CComponent->__call('queryRowl', Array)
#1 Z:\domains\localhost\blogYii\protected\controllers\DatabaseController.php(32): CDbCommand->queryRowl()
#2 Z:\domains\localhost\blogYii\framework\web\actions\CInlineAction.php(49): DatabaseController->actionDao()
#3 Z:\domains\localhost\blogYii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 Z:\domains\localhost\blogYii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 Z:\domains\localhost\blogYii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(282): CController->run('dao')
#7 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('database/dao')
#8 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#9 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#10 {main}
REQUEST_URI=/blogYii/database/dao
---
2015/07/29 17:12:27 [error] [system.db.CDbCommand] Не удалось выполнить CDbCommand::execute(): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '// запрос для ИЗМЕНЕНИЯ данных UPDATE
                 ' at line 1. Выполнявшийся SQL-запрос:   // запрос для ИЗМЕНЕНИЯ данных UPDATE
                      update into tbl_user set
                      username = 'test9',
                      password = '123456789',
                      email = 'test9@domain.com',
                      name = 'Test9',
                      fname = 'Test9 Test9'
                      where id = 3
                      .
2015/07/29 17:12:27 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand не удалось исполнить SQL-запрос: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '// запрос для ИЗМЕНЕНИЯ данных UPDATE
                 ' at line 1' in Z:\domains\localhost\blogYii\framework\db\CDbCommand.php:358
Stack trace:
#0 Z:\domains\localhost\blogYii\protected\controllers\DatabaseController.php(55): CDbCommand->execute()
#1 Z:\domains\localhost\blogYii\framework\web\actions\CInlineAction.php(49): DatabaseController->actionDao()
#2 Z:\domains\localhost\blogYii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 Z:\domains\localhost\blogYii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 Z:\domains\localhost\blogYii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(282): CController->run('dao')
#6 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('database/dao')
#7 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#8 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#9 {main}
REQUEST_URI=/blogYii/database/dao
---
2015/07/29 17:14:57 [error] [system.db.CDbCommand] Не удалось выполнить CDbCommand::execute(): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'into tbl_user set
                      username = 'test9',
                  ' at line 1. Выполнявшийся SQL-запрос:   
                      update into tbl_user set
                      username = 'test9',
                      password = '123456789',
                      email = 'test9@domain.com',
                      name = 'Test9',
                      fname = 'Test9 Test9'
                      where id = 3
                      .
2015/07/29 17:14:57 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand не удалось исполнить SQL-запрос: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'into tbl_user set
                      username = 'test9',
                  ' at line 1' in Z:\domains\localhost\blogYii\framework\db\CDbCommand.php:358
Stack trace:
#0 Z:\domains\localhost\blogYii\protected\controllers\DatabaseController.php(61): CDbCommand->execute()
#1 Z:\domains\localhost\blogYii\framework\web\actions\CInlineAction.php(49): DatabaseController->actionDao()
#2 Z:\domains\localhost\blogYii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 Z:\domains\localhost\blogYii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 Z:\domains\localhost\blogYii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(282): CController->run('dao')
#6 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('database/dao')
#7 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#8 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#9 {main}
REQUEST_URI=/blogYii/database/dao
---
2015/07/29 17:16:53 [error] [system.db.CDbCommand] Не удалось выполнить CDbCommand::execute(): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'into tbl_user set
                      username = 'test9',
                  ' at line 1. Выполнявшийся SQL-запрос: 
                      update into tbl_user set
                      username = 'test9',
                      password = '123456789',
                      email = 'test9@domain.com',
                      name = 'Test9',
                      fname = 'Test9 Test9'
                      where id = 3
                      .
2015/07/29 17:16:53 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand не удалось исполнить SQL-запрос: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'into tbl_user set
                      username = 'test9',
                  ' at line 1' in Z:\domains\localhost\blogYii\framework\db\CDbCommand.php:358
Stack trace:
#0 Z:\domains\localhost\blogYii\protected\controllers\DatabaseController.php(61): CDbCommand->execute()
#1 Z:\domains\localhost\blogYii\framework\web\actions\CInlineAction.php(49): DatabaseController->actionDao()
#2 Z:\domains\localhost\blogYii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 Z:\domains\localhost\blogYii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 Z:\domains\localhost\blogYii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(282): CController->run('dao')
#6 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('database/dao')
#7 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#8 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#9 {main}
REQUEST_URI=/blogYii/database/dao
---
2015/07/30 18:17:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "ar".' in Z:\domains\localhost\blogYii\framework\web\CController.php:483
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\web\CController.php(270): CController->missingAction('ar')
#1 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(282): CController->run('ar')
#2 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('database/ar')
#3 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#5 {main}
REQUEST_URI=/blogYii/database/ar
---
2015/07/30 19:08:54 [error] [php] array_merge(): Argument #2 is not an array (Z:\domains\localhost\blogYii\framework\db\schema\CDbCriteria.php:521)
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\db\ar\CActiveRecord.php(1349): User->applyScopes()
#1 Z:\domains\localhost\blogYii\framework\db\ar\CActiveRecord.php(1475): User->query()
#2 Z:\domains\localhost\blogYii\protected\controllers\DatabaseController.php(113): User->findAll()
#3 Z:\domains\localhost\blogYii\framework\web\actions\CInlineAction.php(49): DatabaseController->actionAr()
#4 Z:\domains\localhost\blogYii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 Z:\domains\localhost\blogYii\framework\web\CController.php(286): DatabaseController->runAction()
#6 Z:\domains\localhost\blogYii\framework\web\CController.php(265): DatabaseController->runActionWithFilters()
#7 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(282): DatabaseController->run()
#8 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 Z:\domains\localhost\blogYii\index.php(11): CWebApplication->run()
REQUEST_URI=/blogYii/database/ar
2015/07/30 19:19:45 [error] [exception.CException] exception 'CException' with message 'В классе User и его поведениях не найден метод или замыкание с именем "active,id".' in Z:\domains\localhost\blogYii\framework\base\CComponent.php:266
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\db\ar\CActiveRecord.php(227): CComponent->__call('active,id', Array)
#1 [internal function]: CActiveRecord->__call('active,id', Array)
#2 [internal function]: User->active,id()
#3 Z:\domains\localhost\blogYii\framework\db\ar\CActiveRecord.php(1403): call_user_func_array(Array, Array)
#4 Z:\domains\localhost\blogYii\framework\db\ar\CActiveRecord.php(1349): CActiveRecord->applyScopes(Object(CDbCriteria))
#5 Z:\domains\localhost\blogYii\framework\db\ar\CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#6 Z:\domains\localhost\blogYii\protected\controllers\DatabaseController.php(113): CActiveRecord->findAll(Object(CDbCriteria))
#7 Z:\domains\localhost\blogYii\framework\web\actions\CInlineAction.php(49): DatabaseController->actionAr()
#8 Z:\domains\localhost\blogYii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 Z:\domains\localhost\blogYii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 Z:\domains\localhost\blogYii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(282): CController->run('ar')
#12 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('database/ar')
#13 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#14 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#15 {main}
REQUEST_URI=/blogYii/database/ar
---
2015/07/31 17:47:32 [error] [exception.CException] exception 'CException' with message 'Свойство "dataProvider" не может быть пустым.' in Z:\domains\localhost\blogYii\framework\zii\widgets\CBaseListView.php:123
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\zii\widgets\grid\CGridView.php(339): CBaseListView->init()
#1 Z:\domains\localhost\blogYii\framework\web\CBaseController.php(147): CGridView->init()
#2 Z:\domains\localhost\blogYii\framework\web\CBaseController.php(180): CBaseController->createWidget('zii.widgets.gri...', Array)
#3 Z:\domains\localhost\blogYii\protected\views\database\provider.php(7): CBaseController->widget('zii.widgets.gri...', Array)
#4 Z:\domains\localhost\blogYii\framework\web\CBaseController.php(126): require('Z:\\domains\\loca...')
#5 Z:\domains\localhost\blogYii\framework\web\CBaseController.php(95): CBaseController->renderInternal('Z:\\domains\\loca...', Array, true)
#6 Z:\domains\localhost\blogYii\framework\web\CController.php(869): CBaseController->renderFile('Z:\\domains\\loca...', Array, true)
#7 Z:\domains\localhost\blogYii\framework\web\CController.php(782): CController->renderPartial('provider', Array, true)
#8 Z:\domains\localhost\blogYii\protected\controllers\DatabaseController.php(128): CController->render('provider', Array)
#9 Z:\domains\localhost\blogYii\framework\web\actions\CInlineAction.php(49): DatabaseController->actionProvider()
#10 Z:\domains\localhost\blogYii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 Z:\domains\localhost\blogYii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#12 Z:\domains\localhost\blogYii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(282): CController->run('provider')
#14 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('database/provid...')
#15 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#16 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#17 {main}
REQUEST_URI=/blogYii/database/provider
---
2015/07/31 17:51:59 [error] [exception.CException] exception 'CException' with message 'Свойство "dataProvider" не может быть пустым.' in Z:\domains\localhost\blogYii\framework\zii\widgets\CBaseListView.php:123
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\zii\widgets\grid\CGridView.php(339): CBaseListView->init()
#1 Z:\domains\localhost\blogYii\framework\web\CBaseController.php(147): CGridView->init()
#2 Z:\domains\localhost\blogYii\framework\web\CBaseController.php(180): CBaseController->createWidget('zii.widgets.gri...', Array)
#3 Z:\domains\localhost\blogYii\protected\views\database\provider.php(7): CBaseController->widget('zii.widgets.gri...', Array)
#4 Z:\domains\localhost\blogYii\framework\web\CBaseController.php(126): require('Z:\\domains\\loca...')
#5 Z:\domains\localhost\blogYii\framework\web\CBaseController.php(95): CBaseController->renderInternal('Z:\\domains\\loca...', Array, true)
#6 Z:\domains\localhost\blogYii\framework\web\CController.php(869): CBaseController->renderFile('Z:\\domains\\loca...', Array, true)
#7 Z:\domains\localhost\blogYii\framework\web\CController.php(782): CController->renderPartial('provider', Array, true)
#8 Z:\domains\localhost\blogYii\protected\controllers\DatabaseController.php(128): CController->render('provider', Array)
#9 Z:\domains\localhost\blogYii\framework\web\actions\CInlineAction.php(49): DatabaseController->actionProvider()
#10 Z:\domains\localhost\blogYii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 Z:\domains\localhost\blogYii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#12 Z:\domains\localhost\blogYii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(282): CController->run('provider')
#14 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('database/provid...')
#15 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#16 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#17 {main}
REQUEST_URI=/blogYii/database/provider
---
2015/07/31 18:00:08 [error] [exception.CException] exception 'CException' with message 'Свойство "dataProvider" не может быть пустым.' in Z:\domains\localhost\blogYii\framework\zii\widgets\CBaseListView.php:123
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\zii\widgets\grid\CGridView.php(339): CBaseListView->init()
#1 Z:\domains\localhost\blogYii\framework\web\CBaseController.php(147): CGridView->init()
#2 Z:\domains\localhost\blogYii\framework\web\CBaseController.php(180): CBaseController->createWidget('zii.widgets.gri...', Array)
#3 Z:\domains\localhost\blogYii\protected\views\database\provider.php(16): CBaseController->widget('zii.widgets.gri...', Array)
#4 Z:\domains\localhost\blogYii\framework\web\CBaseController.php(126): require('Z:\\domains\\loca...')
#5 Z:\domains\localhost\blogYii\framework\web\CBaseController.php(95): CBaseController->renderInternal('Z:\\domains\\loca...', Array, true)
#6 Z:\domains\localhost\blogYii\framework\web\CController.php(869): CBaseController->renderFile('Z:\\domains\\loca...', Array, true)
#7 Z:\domains\localhost\blogYii\framework\web\CController.php(782): CController->renderPartial('provider', Array, true)
#8 Z:\domains\localhost\blogYii\protected\controllers\DatabaseController.php(128): CController->render('provider', Array)
#9 Z:\domains\localhost\blogYii\framework\web\actions\CInlineAction.php(49): DatabaseController->actionProvider()
#10 Z:\domains\localhost\blogYii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 Z:\domains\localhost\blogYii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#12 Z:\domains\localhost\blogYii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(282): CController->run('provider')
#14 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('database/provid...')
#15 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#16 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#17 {main}
REQUEST_URI=/blogYii/database/provider
---
2015/08/02 17:31:29 [error] [php] file_get_contents(Z:/domains/localhost/blogYii/dependency.txt): failed to open stream: No such file or directory (Z:\domains\localhost\blogYii\protected\controllers\CacheController.php:14)
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\web\CController.php(308): CInlineAction->runWithParams()
#1 Z:\domains\localhost\blogYii\framework\web\CController.php(286): CacheController->runAction()
#2 Z:\domains\localhost\blogYii\framework\web\CController.php(265): CacheController->runActionWithFilters()
#3 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(282): CacheController->run()
#4 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#5 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#6 Z:\domains\localhost\blogYii\index.php(11): CWebApplication->run()
REQUEST_URI=/blogYii/cache
2015/08/02 17:37:18 [error] [php] file_get_contents(Z:/domains/localhost/blogYii/dependency.txt): failed to open stream: No such file or directory (Z:\domains\localhost\blogYii\protected\controllers\CacheController.php:14)
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\web\CController.php(308): CInlineAction->runWithParams()
#1 Z:\domains\localhost\blogYii\framework\web\CController.php(286): CacheController->runAction()
#2 Z:\domains\localhost\blogYii\framework\web\CController.php(265): CacheController->runActionWithFilters()
#3 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(282): CacheController->run()
#4 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#5 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#6 Z:\domains\localhost\blogYii\index.php(11): CWebApplication->run()
REQUEST_URI=/blogYii/cache
2015/08/02 18:15:24 [error] [exception.CException] exception 'CException' with message 'Не определено свойство "CDbConnection.achemaCachingDuration".' in Z:\domains\localhost\blogYii\framework\base\CComponent.php:173
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\YiiBase.php(220): CComponent->__set('achemaCachingDu...', 1000)
#1 Z:\domains\localhost\blogYii\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#2 Z:\domains\localhost\blogYii\framework\base\CModule.php(103): CModule->getComponent('db')
#3 Z:\domains\localhost\blogYii\protected\controllers\CacheController.php(21): CModule->__get('db')
#4 Z:\domains\localhost\blogYii\framework\web\actions\CInlineAction.php(49): CacheController->actionIndex()
#5 Z:\domains\localhost\blogYii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#6 Z:\domains\localhost\blogYii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#7 Z:\domains\localhost\blogYii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(282): CController->run('')
#9 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('cache')
#10 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#11 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#12 {main}
REQUEST_URI=/blogYii/cache
---
2015/08/02 18:15:52 [error] [exception.CException] exception 'CException' with message 'Не определено свойство "CDbConnection.chemaCachingDuration".' in Z:\domains\localhost\blogYii\framework\base\CComponent.php:173
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\YiiBase.php(220): CComponent->__set('chemaCachingDur...', 1000)
#1 Z:\domains\localhost\blogYii\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#2 Z:\domains\localhost\blogYii\framework\base\CModule.php(103): CModule->getComponent('db')
#3 Z:\domains\localhost\blogYii\protected\controllers\CacheController.php(21): CModule->__get('db')
#4 Z:\domains\localhost\blogYii\framework\web\actions\CInlineAction.php(49): CacheController->actionIndex()
#5 Z:\domains\localhost\blogYii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#6 Z:\domains\localhost\blogYii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#7 Z:\domains\localhost\blogYii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(282): CController->run('')
#9 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('cache')
#10 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#11 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#12 {main}
REQUEST_URI=/blogYii/cache
---
2015/08/02 19:00:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "page".' in Z:\domains\localhost\blogYii\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('page')
#1 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blogYii/page
---
2015/08/02 19:00:50 [error] [exception.CException] exception 'CException' with message 'Контроллер CacheController не может найти представление "page".' in Z:\domains\localhost\blogYii\framework\web\CController.php:878
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\web\CController.php(782): CController->renderPartial('page', NULL, true)
#1 Z:\domains\localhost\blogYii\protected\controllers\CacheController.php(41): CController->render('page')
#2 Z:\domains\localhost\blogYii\framework\web\actions\CInlineAction.php(49): CacheController->actionPage()
#3 Z:\domains\localhost\blogYii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 Z:\domains\localhost\blogYii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 Z:\domains\localhost\blogYii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(282): CController->run('page')
#7 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('cache/page')
#8 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#9 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#10 {main}
REQUEST_URI=/blogYii/cache/page
---
2015/08/02 19:02:35 [error] [exception.CException] exception 'CException' with message 'Контроллер CacheController не может найти представление "page".' in Z:\domains\localhost\blogYii\framework\web\CController.php:878
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\web\CController.php(782): CController->renderPartial('page', NULL, true)
#1 Z:\domains\localhost\blogYii\protected\controllers\CacheController.php(41): CController->render('page')
#2 Z:\domains\localhost\blogYii\framework\web\actions\CInlineAction.php(49): CacheController->actionPage()
#3 Z:\domains\localhost\blogYii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 Z:\domains\localhost\blogYii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 Z:\domains\localhost\blogYii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(282): CController->run('page')
#7 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('cache/page')
#8 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#9 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#10 {main}
REQUEST_URI=/blogYii/cache/page
---
2015/08/02 19:22:49 [error] [exception.CException] exception 'CException' with message 'Контроллер CacheController не может найти представление "page".' in Z:\domains\localhost\blogYii\framework\web\CController.php:878
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\web\CController.php(782): CController->renderPartial('page', NULL, true)
#1 Z:\domains\localhost\blogYii\protected\controllers\CacheController.php(41): CController->render('page')
#2 Z:\domains\localhost\blogYii\framework\web\actions\CInlineAction.php(49): CacheController->actionPage()
#3 Z:\domains\localhost\blogYii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 Z:\domains\localhost\blogYii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 Z:\domains\localhost\blogYii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(282): CController->run('page')
#7 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('cache/page')
#8 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#9 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#10 {main}
REQUEST_URI=/blogYii/cache/page
---
2015/08/02 19:27:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "page".' in Z:\domains\localhost\blogYii\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('page')
#1 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blogYii/page
---
2015/08/02 19:28:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "page".' in Z:\domains\localhost\blogYii\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('page')
#1 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blogYii/page
---
2015/08/02 19:28:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "page".' in Z:\domains\localhost\blogYii\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('page')
#1 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blogYii/page
---
2015/08/02 19:28:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "page".' in Z:\domains\localhost\blogYii\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('page')
#1 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blogYii/page
---
2015/08/02 19:30:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "page".' in Z:\domains\localhost\blogYii\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('page')
#1 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blogYii/page
---
2015/08/02 19:32:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "page".' in Z:\domains\localhost\blogYii\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('page')
#1 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blogYii/page
---
2015/08/06 18:14:43 [error] [exception.CException] exception 'CException' with message 'В классе BehaviorController и его поведениях не найден метод или замыкание с именем "getDate".' in Z:\domains\localhost\blogYii\framework\base\CComponent.php:266
Stack trace:
#0 Z:\domains\localhost\blogYii\protected\controllers\BehaviorController.php(23): CComponent->__call('getDate', Array)
#1 Z:\domains\localhost\blogYii\protected\controllers\BehaviorController.php(23): BehaviorController->getDate()
#2 Z:\domains\localhost\blogYii\framework\web\actions\CInlineAction.php(49): BehaviorController->actionIndex()
#3 Z:\domains\localhost\blogYii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 Z:\domains\localhost\blogYii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 Z:\domains\localhost\blogYii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(282): CController->run('')
#7 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('behavior')
#8 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#9 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#10 {main}
REQUEST_URI=/blogYii/behavior
---
2015/08/06 18:19:42 [error] [exception.CException] exception 'CException' with message 'В классе BehaviorController и его поведениях не найден метод или замыкание с именем "getDate".' in Z:\domains\localhost\blogYii\framework\base\CComponent.php:266
Stack trace:
#0 Z:\domains\localhost\blogYii\protected\controllers\BehaviorController.php(21): CComponent->__call('getDate', Array)
#1 Z:\domains\localhost\blogYii\protected\controllers\BehaviorController.php(21): BehaviorController->getDate()
#2 Z:\domains\localhost\blogYii\framework\web\actions\CInlineAction.php(49): BehaviorController->actionIndex()
#3 Z:\domains\localhost\blogYii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 Z:\domains\localhost\blogYii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 Z:\domains\localhost\blogYii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(282): CController->run('')
#7 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('behavior')
#8 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#9 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#10 {main}
REQUEST_URI=/blogYii/behavior
---
2015/08/10 18:28:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "createurl".' in Z:\domains\localhost\blogYii\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('createurl')
#1 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blogYii/createurl
---
2015/08/10 18:35:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Невозможно обработать запрос "createurl".' in Z:\domains\localhost\blogYii\framework\web\CWebApplication.php:286
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('createurl')
#1 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#3 {main}
REQUEST_URI=/blogYii/createurl
---
2015/08/13 17:06:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Системе не удалось найти запрашиваемое действие "db".' in Z:\domains\localhost\blogYii\framework\web\CController.php:483
Stack trace:
#0 Z:\domains\localhost\blogYii\framework\web\CController.php(270): CController->missingAction('db')
#1 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(282): CController->run('db')
#2 Z:\domains\localhost\blogYii\framework\web\CWebApplication.php(141): CWebApplication->runController('ajax/db')
#3 Z:\domains\localhost\blogYii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 Z:\domains\localhost\blogYii\index.php(11): CApplication->run()
#5 {main}
REQUEST_URI=/blogYii/ajax/db
---
